// portfolio-angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { CtaComponent } from './cta/cta.component';
import { HeaderSocialsComponent } from './header-socials/header-socials.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CtaComponent, HeaderSocialsComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {}

<header>
  <div class="container header__container glass">
    <span class="header__eyebrow">Intermediate Software Engineer</span>
    <h1 class="header__name">Nkosinathi Tshaphile</h1>
    <h5 class="text-light header__role">Building AI-driven products with Angular, .NET Core and Claude Code at LexisNexis.</h5>
    <app-cta></app-cta>
    <app-header-socials></app-header-socials>
    <a href="#contact" class="scroll__down">Scroll Down</a>
  </div>
</header>

// src/components/header/Header.jsx
import React from "react";
import "./header.css";
import CTA from "./CTA";
import me from "../../assets/me.png";
import HeaderSocials from "./HeaderSocials";
const Header = () => {
  return (
    <header>
      <div className="container header__container">
        <h5>Hello I'm</h5>
        <h1>Nkosinathi Tshaphile</h1>
        <h5 className="text-light">Software Developer</h5>
        <CTA />
        <HeaderSocials />

        <div className="me">
          <img src={me} alt="me" />
        </div>

        <a href="#contact" className="scroll__down">
          Scroll Down
        </a>
      </div>
    </header>
  );
};

export default Header;
