// src/components/contact/Contact.jsx
import React from "react";
import "./contact.css";
import { MdOutlineEmail } from "react-icons/md";
import { RiMessengerLine } from "react-icons/ri";
import { BsWhatsapp } from "react-icons/bs";

const Contact = () => {
  return (
    <section id="contact">
      <h5>Get In Touch</h5>
      <h2>Contact Me</h2>

      <div className="container contact__container">
        <div className="contact__options">
          <article className="contact__option">
            <MdOutlineEmail className="contact__option-icon" />
            <h4>Email</h4>
            <h5>tshaphilenkosinathi@gmail.com</h5>
            <a href="mailto:tshaphilenkosinathi@gmail.com" target="_blank">
              Send me an E-mail
            </a>
          </article>
          <article className="contact__option">
            <BsWhatsapp className="contact__option-icon" />
            <h4>WhatsApp</h4>
            <h5>+27 62 033 8048</h5>
            <a
              href="https://api.whatsapp.com/send?phone=+27620338048"
              target="_blank"
            >
              Send me a message
            </a>
          </article>
          <article className="contact__option">
            <RiMessengerLine className="contact__option-icon" />
            <h4>Messenger</h4>
            <h5>Nkosinathi Tshaphile</h5>
            <a href="https://m.me/nkosinathi.tshaphile" target="_blank">
              Send me a DM
            </a>
          </article>
        </div>
        {/**END OF CONTACT OPTIONS */}
        <form action="">
          <input
            type="text"
            name="name"
            placeholder="Your Full Name"
            required
          />
          <input type="email" name="email" placeholder="Your Email" required />
          <textarea
            name="message"
            rows="7"
            placeholder="Your Message"
            required
          ></textarea>
          <button type="submit" className="btn btn-primary">
            Send Message
          </button>
        </form>
      </div>
    </section>
  );
};

export default Contact;

// portfolio-angular/src/app/components/contact/contact.component.ts
import { Component, inject } from '@angular/core';
import { PortfolioService } from '../../services/portfolio.service';

@Component({
  selector: 'app-contact',
  standalone: true,
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {
  private portfolioService = inject(PortfolioService);
  personalInfo = this.portfolioService.getPersonalInfo();
  
  getWhatsAppLink() {
    return this.portfolioService.getWhatsAppLink();
  }
}

<section id="contact" class="contact">
  <div class="container">
    <p class="section-subtitle">Get In Touch</p>
    <h2 class="section-title">Contact Me</h2>
    
    <div class="contact-grid">
      <div class="contact-card">
        <div class="contact-icon">📧</div>
        <h3>Email</h3>
        <p>{{ personalInfo.email }}</p>
        <a [href]="'mailto:' + personalInfo.email" class="btn btn-primary">Send me an E-mail</a>
      </div>
      
      <div class="contact-card">
        <div class="contact-icon">💬</div>
        <h3>WhatsApp</h3>
        <p>{{ personalInfo.phone }}</p>
        <a [href]="getWhatsAppLink()" target="_blank" class="btn btn-primary">Send me a WhatsApp message</a>
      </div>
    </div>
  </div>
</section>
