// src/components/header/CTA.jsx
import React from "react";
import CV from "../../assets/cv.pdf";
const CTA = () => {
  return (
    <div className="cta">
      <a href={CV} download className="btn">
        Download CV
      </a>
      <a href="#contact" className="btn btn-primary">
        Let's Chat
      </a>
    </div>
  );
};

export default CTA;

// portfolio-angular/src/app/components/header/cta/cta.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-cta',
  standalone: true,
  imports: [],
  templateUrl: './cta.component.html',
  styleUrl: './cta.component.css'
})
export class CtaComponent {}

<div class="cta">
  <a href="/assets/cv.pdf" download class="btn">Download CV</a>
  <a href="#contact" class="btn btn-primary">Let's Chat</a>
</div>
